runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /static/img
  static_dir: static/img

- url: /.*
  script: blog.app

libraries:
- name: jinja2
  version: latest